#!/bin/bash
set -u

if ls | grep "results"; then

    echo "Continuing from previous working directory: results/"
    
    else
    
        mkdir results
        MKDIR results/pdbqt
fi

eval "$(conda shell.bash hook)"

LIST="astex_diverse_set_ids.txt"
FOLDER_NAME="astex_diverse_set"
RUN_NAMD="/home/li/Documents/pseudobin/NAMD/namd3"
RESULTS_DIR="/home/li/Desktop/Research Virtual Lab/Redocking Phase/posebusters_paper_data/results"

cat $LIST | tr "\n" " " > ${LIST%.*}_list.txt

#LOOP

N="0"

while [ "$N" -lt "85" ]; do

    N=$(($N + 1))

	NAME=$(awk -v x="$N" '{print $x}' ${LIST%.*}_list.txt)
	PATH_PROT="./${FOLDER_NAME}/${NAME}"

		# Minimization of ligand and fixing of proteins

    cd $PATH_PROT

		conda activate vinagpu

# << source the files >>
						
cat <<EOF > export.sh

		export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
		
EOF

chmod u+x export.sh
source export.sh

# << average coordinates of the reference ligand >>

X=$(grep "0  0" ${NAME}_ligand.sdf | grep -v "V2000" | awk '{print $1}' | datamash mean 1)
Y=$(grep "0  0" ${NAME}_ligand.sdf | grep -v "V2000" | awk '{print $2}' | datamash mean 1)
Z=$(grep "0  0" ${NAME}_ligand.sdf | grep -v "V2000" | awk '{print $3}' | datamash mean 1)

# << minimizing the ligand geometry >>

		obminimize -ff MMFF94 -n 10000 -h ${NAME}_ligand_start_conf.sdf > ${NAME}_ligand.pdb
		
		# << fix the pdb file >>
		
		pdbfixer ${NAME}_protein.pdb \
		--keep-heterogens none \
		--replace-nonstandard \
		--ph=7.45 \
		--add-atoms all \
		--output ${NAME}_proteinf.pdb > /dev/null
		
		# << reconversion of pdb back into mol2: Use Vega or Obabel? >>
		
		vega ${NAME}_ligand.pdb -l GEN -c GASTEIGER -f mol2 -o ${NAME}_ligandf.mol2
		#obabel -ipdb ${NAME}_ligand.pdb -osdf -O ${NAME}_ligandf.sdf

# Minimize/optimize geometry of hydrogens & ascertaining radius of gyration.

cat <<EOF > vmd_psf.pgn

package require autopsf

mol new ${NAME}_proteinf.pdb type pdb waitfor all

mol new ${NAME}_ligand.pdb type pdb waitfor all

autopsf -mol 0 -solvate -ionize

set ligand [ atomselect 1 all ]

set radius_of_gyration [ measure rgyr \$ligand ]

puts "GYRATION: [ expr \$radius_of_gyration * 2.9 ]"

mol delete all

mol new ${NAME}_proteinf_autopsf.pdb type pdb waitfor all

set protein_all [ atomselect top all ]

set protein_h [ atomselect top "hydrogen" ]

\$protein_all set beta 1
\$protein_h set beta 0

\$protein_all writepdb ${NAME}_fixedAtom.pdb



exit

EOF

# NAMD minimization configuration

cat <<EOF > namd_minimization.namd
# NAMD Config file - autogenerated by NAMDgui plugin
# Author: Jan Saam,  saam@charite.de

# input
coordinates             ${NAME}_proteinf_autopsf.pdb
structure               ${NAME}_proteinf_autopsf.psf
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_prot.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_na.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_lipid.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_carb.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_cgenff.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/toppar_water_ions_namd.str
paratypecharmm          on

# output
set output              ${NAME}
outputname              \$output
dcdfile                 \${output}.dcd
xstFile                 \${output}.xst
dcdfreq                 50
xstFreq                 50

binaryoutput            no
binaryrestart           no
outputEnergies          100
restartfreq             1000

fixedAtoms              on
fixedAtomsCol           B
fixedAtomsFile          ${NAME}_fixedAtom.pdb

# Basic dynamics
exclude                 scaled1-4
1-4scaling              1
COMmotion               no
dielectric              1.0

# Simulation space partitioning
switching               on
switchdist              9
cutoff                  10
pairlistdist            12

# Multiple timestepping
firsttimestep           0
timestep                1
stepspercycle           20
nonbondedFreq           2
fullElectFrequency      4

# Temperature control

set temperature         310
temperature             \$temperature;  # initial temperature


# Scripting

minimize            500
EOF

	# VMD setting of PDBs

		vmd -dispdev none -e vmd_psf.pgn > vmd_psf.log

	GYRATION=$(grep "GYRATION:" vmd_psf.log | awk '{print $2}')

	#NAMD execution of minimization

	$RUN_NAMD +p4 +setcpuaffinity +idlepoll +devices 0 namd_minimization.namd > namd_minimization.log

#Saving of the .dcd file

cat <<EOF > vmd_save_dcd.pgn

mol new ${NAME}_proteinf_autopsf.psf type psf waitfor all
mol addfile ${NAME}.dcd type dcd waitfor all

set protein [atomselect top protein]

animate goto 999

\$protein frame now

\$protein writepdb ${NAME}_protein-honly.pdb

exit

EOF

   # << PATH needed for pdbqt creation of protein file >>

	#VMD saving of .dcd file

	vmd -dispdev none -e vmd_save_dcd.pgn  > vmd_save_dcd.log

RUN_VINACUDA="/home/li/Documents/pseudobin/Vina-CUDA/Vina-CUDA_v1.1/Vina-GPU-2-1-CUDA"
RUN_VINAGPU="/home/li/Documents/pseudobin/Vina-GPU-2.1/QuickVina2-GPU-2.1/QuickVina2-GPU-2-1"
RUN_VINACPU="/home/li/Documents/pseudobin/Vina/vina"
GNINA="/home/li/Documents/pseudobin/gnina/gnina"
VINA_SPLIT="/home/li/Documents/pseudobin/vina_split/vina_split"
RECEPTOR_PY="/home/li/Documents/pseudobin/mgltools_x86_64Linux2_1.5.7/MGLToolsPckgs/AutoDockTools/Utilities24/"
PYTHONSH="/home/li/Documents/pseudobin/mgltools_x86_64Linux2_1.5.7/bin/pythonsh"


    # << conversion of pdbqrs -> pdbqt for receptor; meeko for ligand >>

    conda activate adt_utils

    $PYTHONSH \ ${RECEPTOR_PY}/prepare_receptor.py -r ${NAME}_protein-honly.pdb -o ${NAME}_protein-honly.pdbqs
    $PYTHONSH \ ${RECEPTOR_PY}/pdbqs_to_pdbqt.py -s ${NAME}_protein-honly -C -o ${NAME}_protein-honly.pdbqt
	
	# << meeko or ADT? >>
	
	$PYTHONSH \ ${RECEPTOR_PY}/prepare_ligand4.py -l ${NAME}_ligandf.mol2 -o ${NAME}_ligandf.pdbqt
	#conda activate meeko
	
	#mk_prepare_ligand.py -i ${NAME}_ligandf.sdf -o ${NAME}_ligandf.pdbqt
	
	# << end of conversion >>

	# << RUNNING VINA >>

conda activate vinagpu-opencl

cat <<EOF > export.sh

		export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
		
EOF

chmod u+x export.sh
source export.sh

	    $RUN_VINAGPU \
		--receptor ${NAME}_protein-honly.pdbqt \
		--ligand ${NAME}_ligandf.pdbqt \
		--size_x $GYRATION \
		--size_y $GYRATION \
		--size_z $GYRATION \
		--center_x $X \
		--center_y $Y \
		--center_z $Z \
		--num_modes 200 \
		--opencl_binary_path "/home/li/Documents/pseudobin/Vina-GPU-2.1/QuickVina2-GPU-2.1/" \
		--search_depth 28 \
		--thread 8000 \
		--out ${NAME}_conf.pdbqt
		
		echo $LD_LIBRARY_PATH

#<< THE FILE WILL TURN INTO ${NAME}_conf_ligand_1/2/3/4/... >>

$VINA_SPLIT --input ${NAME}_conf.pdbqt

# << GNINA optimization >>

conda activate gnina

cat <<EOF > export.sh

		export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
		
EOF

chmod u+x export.sh
source export.sh > /dev/null

# << GNINA parameters >>

for ligands in *conf_ligand_*.pdbqt; do

	$GNINA -r ${NAME}_protein-honly.pdbqt -l $ligands --exhaustiveness 16 --minimize --cnn_scoring rescore -o ${ligands%.*}_final_rescore.pdbqt > /dev/null &
	$GNINA -r ${NAME}_protein-honly.pdbqt -l $ligands --exhaustiveness 16 --minimize --cnn_scoring refinement -o ${ligands%.*}_final_refinement.pdbqt > /dev/null

echo "Minimization done for: ${NAME}"
echo "Status:"
echo "$ligands"

done

# << Culling of badly scored ligands. >>

echo ""
echo "KEPT CONFORMATIONS:"

for scores in *_final_*.pdbqt; do

    if grep "CNNscore" $scores | awk -v x="$scores" '{ if ($3 > 0.70) {print x " " $3; exit 1}}'; then
	
	   rm $scores
	
	else
	
		mv $scores ../../results
		
		fi
done

# << Removal of inf values "intra" >>

mv ${NAME}_ligandf.mol2 ../../results
cp ${NAME}_ligand.sdf ../../results

cd ../../results

# << Checkpoint for the processed pdbqt files >>

for qt in ${NAME}*.pdbqt; do

    echo "Converting file into .mol2: $qt"

    obabel -ipdbqt $qt -omol2 -O ${qt%.*}.mol2
    
        if obrms ${NAME}_ligandf.mol2 ${qt%.*}.mol2 | grep -o "inf"; then
        
            echo "Cleaning up the data for: $qt"
        
                rm ${qt%.*}.mol2
                
                else
                
                    echo "Seems fine for $qt, moving on..."
                  
                    mv $qt pdbqt/
                
                # << Documentation of results. >>
                
                    obabel -isdf ${NAME}_ligand.sdf -omol2 -O ${NAME}_ligand.mol2
                
                    obrms ${NAME}_ligand.mol2 ${qt%.*}.mol2 -m >> redock_rescore.csv
                    
                fi
    
    done

# << RMSD Convergenece >>

    OUTPUT=$(cat redock_rescore.csv | awk '{print $3}' | datamash mean 1)

    echo "RMSD_CONVERGENCE(${NAME}): $OUTPUT" >> RMSD_convergence.csv
    
# << Moving the pdbqt files into a specific folder >>

cd ..

done