#!/bin/bash
set -u

eval "$(conda shell.bash hook)"

LIST="astex_diverse_set_ids.txt"
FOLDER_NAME="astex_diverse_set"
RUN_NAMD="/home/li/Documents/pseudobin/NAMD/namd3"

cat $LIST | tr "\n" " " > ${LIST%.*}_list.txt

#LOOP

N="0"

while [ "$N" -lt "85" ]; do

    N=$(($N + 1))

	NAME=$(awk -v x="$N" '{print $x}' ${LIST%.*}_list.txt)
	PATH_PROT="./${FOLDER_NAME}/${NAME}"

		# Minimization of ligand and fixing of proteins

    cd $PATH_PROT

		conda activate vinagpu

# << source the files >>
						
cat <<EOF > export.sh

		export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
		
EOF

chmod u+x export.sh
source export.sh

# << average coordinates of the reference ligand >>

X=$(grep "0  0" ${NAME}_ligand.sdf | grep -v "V2000" | awk '{print $1}' | datamash mean 1)
Y=$(grep "0  0" ${NAME}_ligand.sdf | grep -v "V2000" | awk '{print $2}' | datamash mean 1)
Z=$(grep "0  0" ${NAME}_ligand.sdf | grep -v "V2000" | awk '{print $3}' | datamash mean 1)

# << minimizing the ligand geometry >>

		obminimize -ff MMFF94 -n 10000 -h ${NAME}_ligand_start_conf.sdf > ${NAME}_ligand.pdb
		
		# << fix the pdb file >>
		
		pdbfixer ${NAME}_protein.pdb \
		--keep-heterogens none \
		--replace-nonstandard \
		--ph=7.45 \
		--add-atoms all \
		--output ${NAME}_proteinf.pdb > /dev/null
		
		# << reconversion of pdb back into mol2: Use Vega or Obabel? >>
		
		#vega ${NAME}_ligand.pdb -l GEN -c GASTEIGER -f mol2 -o ${NAME}_ligandf.mol2
		obabel -ipdb ${NAME}_ligand.pdb -osdf -O ${NAME}_ligandf.sdf

# Minimize/optimize geometry of hydrogens & ascertaining radius of gyration.

cat <<EOF > vmd_psf.pgn

package require autopsf

mol new ${NAME}_proteinf.pdb type pdb waitfor all

mol new ${NAME}_ligand.pdb type pdb waitfor all

autopsf -mol 0 -solvate -ionize

set ligand [ atomselect 1 all ]

set radius_of_gyration [ measure rgyr \$ligand ]

puts "GYRATION: [ expr \$radius_of_gyration * 2.9 ]"

mol delete all

mol new ${NAME}_proteinf_autopsf.pdb type pdb waitfor all

set protein_all [ atomselect top all ]

set protein_h [ atomselect top "hydrogen" ]

\$protein_all set beta 1
\$protein_h set beta 0

\$protein_all writepdb ${NAME}_fixedAtom.pdb



exit

EOF

# NAMD minimization configuration

cat <<EOF > namd_minimization.namd
# NAMD Config file - autogenerated by NAMDgui plugin
# Author: Jan Saam,  saam@charite.de

# input
coordinates             ${NAME}_proteinf_autopsf.pdb
structure               ${NAME}_proteinf_autopsf.psf
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_prot.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_na.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_lipid.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_carb.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/par_all36_cgenff.prm
parameters              /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmpar1.5/toppar_water_ions_namd.str
paratypecharmm          on

# output
set output              ${NAME}
outputname              \$output
dcdfile                 \${output}.dcd
xstFile                 \${output}.xst
dcdfreq                 50
xstFreq                 50

binaryoutput            no
binaryrestart           no
outputEnergies          100
restartfreq             1000

fixedAtoms              on
fixedAtomsCol           B
fixedAtomsFile          ${NAME}_fixedAtom.pdb

# Basic dynamics
exclude                 scaled1-4
1-4scaling              1
COMmotion               no
dielectric              1.0

# Simulation space partitioning
switching               on
switchdist              9
cutoff                  10
pairlistdist            12

# Multiple timestepping
firsttimestep           0
timestep                1
stepspercycle           20
nonbondedFreq           2
fullElectFrequency      4

# Temperature control

set temperature         310
temperature             \$temperature;  # initial temperature


# Scripting

minimize            500
EOF

	# VMD setting of PDBs

		vmd -dispdev none -e vmd_psf.pgn > vmd_psf.log

	GYRATION=$(grep "GYRATION:" vmd_psf.log | awk '{print $2}')

	#NAMD execution of minimization

	$RUN_NAMD +p4 +setcpuaffinity +idlepoll +devices 0 namd_minimization.namd > namd_minimization.log

#Saving of the .dcd file

cat <<EOF > vmd_save_dcd.pgn

mol new ${NAME}_proteinf_autopsf.psf type psf waitfor all
mol addfile ${NAME}.dcd type dcd waitfor all

set protein [atomselect top protein]

animate goto 999

\$protein frame now

\$protein writepdb ${NAME}_protein-honly.pdb

exit

EOF

   # << PATH needed for pdbqt creation of protein file >>

	#VMD saving of .dcd file

	vmd -dispdev none -e vmd_save_dcd.pgn  > vmd_save_dcd.log

RUN_VINACUDA="/home/li/Documents/pseudobin/Vina-CUDA/Vina-CUDA_v1.1/Vina-GPU-2-1-CUDA"
RUN_VINAGPU="/home/li/Documents/pseudobin/Vina-GPU-2.1/QuickVina2-GPU-2.1/QuickVina2-GPU-2-1"
RUN_VINACPU="/home/li/Documents/pseudobin/Vina/vina"
VINA_SPLIT="/home/li/Documents/pseudobin/vina_split/vina_split"
RECEPTOR_PY="/home/li/Documents/pseudobin/mgltools_x86_64Linux2_1.5.7/MGLToolsPckgs/AutoDockTools/Utilities24/"
PYTHONSH="/home/li/Documents/pseudobin/mgltools_x86_64Linux2_1.5.7/bin/pythonsh"


    # << conversion of pdbqrs -> pdbqt for receptor; meeko for ligand >>

    conda activate adt_utils

    $PYTHONSH \ ${RECEPTOR_PY}/prepare_receptor.py -r ${NAME}_protein-honly.pdb -o ${NAME}_protein-honly.pdbqs
    $PYTHONSH \ ${RECEPTOR_PY}/pdbqs_to_pdbqt.py -s ${NAME}_protein-honly -C -o ${NAME}_protein-honly.pdbqt
	
	# << meeko or ADT? >>
	
	#$PYTHONSH \ ${RECEPTOR_PY}/prepare_ligand4.py -l ${NAME}_ligand.pdb -o ${NAME}_ligandf.pdbqt
	conda activate meeko
	
	mk_prepare_ligand.py -i ${NAME}_ligandf.sdf -o ${NAME}_ligandf.pdbqt
	
	# << end of conversion >>

	# << RUNNING VINA >>

cat <<EOF > export.sh

		export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
		
EOF

chmod u+x export.sh
source export.sh

	    $RUN_VINACPU \
		--receptor ${NAME}_protein-honly.pdbqt \
		--ligand ${NAME}_ligandf.pdbqt \
		--size_x $GYRATION \
		--size_y $GYRATION \
		--size_z $GYRATION \
		--center_x $X \
		--center_y $Y \
		--center_z $Z \
		--num_modes 10 \
		--exhaustiveness 16 \
		--cpu 12 \
		--out ${NAME}_conf.pdbqt
		
		echo $LD_LIBRARY_PATH

#<< THE FILE WILL TURN INTO ${NAME}_conf_ligand_1/2/3/4/... >>

$VINA_SPLIT --input ${NAME}_conf.pdbqt

# GNINA optimization

conda activate gnina

cat <<EOF > export.sh

		export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
		
EOF

chmod u+x export.sh
source export.sh

GNINA="/home/li/Documents/pseudobin/gnina/gnina"

for ligands in *conf_ligand_*.pdbqt; do

	$GNINA -r ${NAME}_protein-honly.pdbqt -l $ligands --minimize --cnn_scoring rescore --cnn default_ensemble  -o ${ligands%.*}_final_default.pdbqt > /dev/null &
	$GNINA -r ${NAME}_protein-honly.pdbqt -l $ligands --minimize --cnn_scoring rescore --cnn all_ensemble -o ${NAME}_final_all.pdbqt & > /dev/null
	$GNINA -r ${NAME}_protein-honly.pdbqt -l $ligands --minimize --cnn_scorin rescore --cnn redocking_ensemble -o ${NAME}_final_redocking.pdbqt > /dev/null

echo "Minimization done for: ${NAME}"

done

# Culling of badly scored ligands.

for scores in *_final_*.pdbqt; do

	if grep "CNNscore:" | awk '{if ($2 > 0.8) {print "Removing low scored ligand conformation."; exit 0}}'; then

		rm $scores

	else

		echo "Keeping ligand conformation: ${scores%.*}" >> kept_list.txt

	# Reconverting the pdbqt back into pdb and mol2.

		obabel -ipdbqt ${NAME}_protein-honly.pdbqt -opdb -O ${NAME}_proteinr.pdb
		vega ${scores} -l -f mol2 -o ${scores%.*}.mol2
	fi

done

conda activate AmberTools25

for sybyl in *.mol2; do

		antechamber -i $sybyl -o ${sybyl%.*}_ac.mol2 -fi mol2 -fo mol2 -c bcc > frcmodification.log

if grep -oE "odd|Odd" frcmodification.log; then

		echo "Uneven electrons found. Neutralizing..."

		antechamber -i $sybyl -o ${sybyl%.*}_ac.mol2 -fi mol2 -fo mol2 -c bcc -nc 1

	else

		echo "All good! Proceeding to tleap..."

fi

	done

#<< creation of inpcrd and prmtop for NAMD >>

for antechamber in *_ac.mol2; do

cat <<EOF > ${antechamber%.*}_tleap.in
source leaprc.protein.ff14SB
source leaprc.gaff2

ligand = loadMol2 $antechamber
loadAmberParams ${antechamber%.*}.frcmod

protein = loadPdb ${NAME}_proteinr.pdb

solvateOct protein TIP3PBOX 1.0
addIons protein Ca+ 0
addIons protein Cl- 0

saveAmberParm ${antechamber%.*}.prmtop ${antechamber%.*}.inpcrd

quit

EOF

# << NAMD parameters for energy minimzation >>

cat <<EOF > complex_minimization.namd
amber		on
ambercoor	${antechamber%.*}.inpcrd
amberparam	${antechamber%.*}.prmtop

# output
set output              template
outputname              $output
dcdfile                 ${output}.dcd
xstFile                 ${output}.xst
dcdfreq                 50
xstFreq                 50

binaryoutput            no
binaryrestart           no
outputEnergies          100
restartfreq             1000

fixedAtoms              on
fixedAtomsCol           B
fixedAtomsFile          ${NAME}_fixedAtom.pdb

# Basic dynamics
exclude                 scaled1-4
1-4scaling              1
COMmotion               no
dielectric              1.0

# Simulation space partitioning
switching               on
switchdist              9
cutoff                  10
pairlistdist            12

# Multiple timestepping
firsttimestep           0
timestep                1
stepspercycle           20
nonbondedFreq           2
fullElectFrequency      4

# Temperature control

set temperature         310
temperature             \$temperature;  # initial temperature


# Scripting

minimize            1000
EOF

sleep 99999999

# << NAMD parameters for NVT equilibriation >>

cat << EOF > complex_nvt.namd

EOF

# << NAMD parameter for NPT equilibriation >>

cat <<EOF > complex_npt.namd

EOF

# << NAMD parameter for MM-GBSA >>

cat << EOF > mmgbsa.namd

EOF

	# tleap production

		tleap -f ${antechamber%.*}_tleap.in


	# NAMD production

		namd +p2 +setcpuaffinity +idlepoll +devices 0 complex_minimization.namd > complex_min.log
		namd +p2 +setcpuaffinity +idlepoll +devices 0 complex_nvt.namd > complex_nvt.log
		namd +p2 +setcpuaffinity +idlepoll +devices 0 complex_npt.namd > complex_npt.log
		namd +p2 +setcpuaffinity +idlepoll +devices 0 mmgbsa.namd > mmgbsa_{antechamber%.*}.log

done

# << MMGBSA results >>

for gbsa_results in *_mmgbsa.dcd; do

cat <<EOF pose_generation.pgn

mol new ${gbsa_results%.*}.psf type psf waitfor all
mol new ${gbsa_results} type dcd waitfor all

set gbsa_ensemble [ atomselect top "hetero" ]

\$gbsa_ensemble writepdb ${gbsa_results%.*}_ensemble.pdb

exit

EOF

	# << convert the pdb to mol2 >>

		vega ${gbsa_results%.*}.pdb -w -f sdf -o ${gbsa_results%.*}_gbsa.sdf
		obrms ${NAME}_ligand.sdf ${gbsa_results%.*}.sdf -m >> ref_rmsd.csv
		awk -v y="${gbsa_results%.*}" '{x+=$3; n++}{print y ": " x/n}' ref_rmsd.csv >> rmsd_convergence.csv

done

cd -

echo "Docking results is done for: ${NAME}"

done
