#!/bin/env bash

input_file="$1"
mode="$2"

if [[ $input_file == "ligand" ]]; then

	if [[ $mode -gt "1" ]]; then

		echo "Converting $mode .pdbqt files per batch"

		echo "Mode: batch"

		ls *.pdb | xargs -P $mode  -I{} sh -c '$0 \ $1/prepare_ligand4.py -l $2 -o ${2%.*}.pdbqt > /dev/null' $mgl_pythonsh $mgl_utils {}

	else

		echo "Converting 1 .pdbqt files per batch"
		echo "Mode: single"

		ls *.pdb | xargs -P $mode  -I{} sh -c '$0 \ $1/prepare_ligand4.py -l $2 -o ${2%.*}.pdbqt > /dev/null' $mgl_pythonsh $mgl_utils {}

	fi

elif [[ $input_file == "protein"  ]]; then

	if [[ $mode -gt "1" ]]; then

		echo "Converting $mode .pdbqt files per batch"

		echo "Mode: batch"

		ls *_min.pdb | xargs -P $mode -I{} sh -c '$0 \ $1/prepare_receptor.py -r $2 -o ${2%.*}.pdbqs > /dev/null' $mgl_pythonsh $mgl_utils {}
		
		ls *_min.pdb | xargs -P $mode -I{} sh -c '$0 \ $1/pdbqs_to_pdbqt.py -s ${2%.*}  -C -o ${2%.*}.pdbqt > /dev/null' $mgl_pythonsh $mgl_utils {}

	else

		echo "Converting $mode .pdbqt files per batch"

		echo "Mode: single"

        ls *_min.pdb | xargs -P $mode -I{} sh -c '$0 \ $1/prepare_receptor.py -r $2 -o ${2%.*}.pdbqs > /dev/null' $mgl_pythonsh $mgl_utils {}

		ls *_min.pdb | xargs -P 1 -I{} sh -c '$0 \ $1/pdbqs_to_pdbqt.py -r $2  -C -o ${2%.*}.pdbqt > /dev/null' $mgl_pythonsh $mgl_utils {}
		
	fi

fi

rm *.pdbqs 2> /dev/null
